name: VerifyDiff

on:
  workflow_dispatch:
    

jobs:
  verifyDiff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Verify Release apkDiff
      run: kotlinc -script .github/workflows/verifyDiff.kts
